# Generated by Django 5.1.3 on 2024-11-27 11:47

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту", max_length=254, verbose_name="Почта"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Выберите страну", max_length=2, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Укажите город", max_length=50, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Укажите улицу", max_length=50, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="Укажите номер дома",
                        max_length=50,
                        verbose_name="Номер дома",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Укажите задолженность",
                        max_digits=10,
                        null=True,
                        verbose_name="Задолженность",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "trade_network_level",
                    models.PositiveIntegerField(
                        choices=[(0, 0), (1, 1), (2, 2)],
                        help_text="Укажите уровень в торговой сети",
                        verbose_name="Уровень в торговой сети",
                    ),
                ),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("factory", "завод"),
                            ("retail network", "розничная сеть"),
                            (
                                "individual entrepreneur",
                                "индивидуальный предприниматель",
                            ),
                        ],
                        help_text="Укажите тип продавца",
                        max_length=30,
                        verbose_name="Тип продавца",
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        blank=True,
                        help_text="Укажите контакты",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to="sellers.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите продукты",
                        null=True,
                        related_name="products",
                        to="products.product",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sellers.seller",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продавец",
                "verbose_name_plural": "Продавцы",
            },
        ),
    ]
