# Generated by Django 5.1.3 on 2024-11-27 12:37

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="contacts",
        ),
        migrations.AddField(
            model_name="seller",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=50,
                null=True,
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Выберите страну",
                max_length=2,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Укажите почту",
                max_length=254,
                null=True,
                verbose_name="Почта",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="house_number",
            field=models.CharField(
                blank=True,
                help_text="Укажите номер дома",
                max_length=50,
                null=True,
                verbose_name="Номер дома",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="street",
            field=models.CharField(
                blank=True,
                help_text="Укажите улицу",
                max_length=50,
                null=True,
                verbose_name="Улица",
            ),
        ),
        migrations.DeleteModel(
            name="Contacts",
        ),
    ]
