# Generated by Django 5.1.3 on 2024-11-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("sellers", "0002_remove_seller_contacts_seller_city_seller_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="products",
            field=models.ManyToManyField(
                help_text="Укажите продукты",
                related_name="products",
                to="products.product",
                verbose_name="Контакты",
            ),
        ),
    ]
