# Generated by Django 5.1.3 on 2024-11-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("sellers", "0003_alter_seller_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="products",
            field=models.ManyToManyField(
                help_text="Укажите продукты",
                related_name="products",
                to="products.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите поставщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sellers.seller",
                verbose_name="Поставщик",
            ),
        ),
    ]
