# Generated by Django 5.1.3 on 2024-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0004_alter_seller_products_alter_seller_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите задолженность",
                max_digits=10,
                verbose_name="Задолженность",
            ),
        ),
    ]
