# Generated by Django 5.1.3 on 2024-11-29 10:29

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0005_alter_seller_debt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="trade_network_level",
        ),
        migrations.AlterField(
            model_name="seller",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите задолженность",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Задолженность",
            ),
        ),
    ]
