# Generated by Django 5.1.3 on 2024-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0006_remove_seller_trade_network_level_alter_seller_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="trade_network_level",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите уровень в торговой сети",
                null=True,
                verbose_name="Уровень в торговой сети",
            ),
        ),
    ]
