# Generated by Django 5.1.3 on 2024-11-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0007_seller_trade_network_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="trade_network_level",
        ),
    ]
