# Generated by Django 5.1.3 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название продукта",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Укажите модель продукта",
                        max_length=100,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату выхода продукта на рынок",
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
